{% set name = "pyquil" %}
{% set version = "3.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquil-{{ version }}.tar.gz
  sha256: 7590e7a1c956d22a68520db9e922c797972f90fcc834590104eaa010562f5bf2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - ipython ^7.21.0optionaltrue
    - nbsphinx ^0.8.6optionaltrue
    - recommonmark ^0.7.1optionaltrue
    - sphinx ^4.0.2optionaltrue
    - sphinx_rtd_theme ^0.5.2optionaltrue
    - types-python-dateutil ^2.8.19
    - types-retry ^0.9.9
    - importlib-metadata >=3.7.3,<5python<3.8
    - lark ^0.11.1
    - networkx ^2.5
    - numpy ^1.21
    - python >=3.7,<4.0
    - qcs-api-client >=0.21.0,<0.22.0
    - retry ^0.9.2
    - rpcq ^3.10.0
    - scipy ^1.6.1
  run_constrained:
    - ipython >=7.21.0,<8.0.0

test:
  imports:
    - pyquil
    - pyquil._parser
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
